development:
  adapter: postgresql
  encoding: unicode
  database: highsimple_dev
  pool: 5
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: highsimple_test
  host: localhost
  port: 5432
